VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IWeldNumber"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function Compacted() As String

End Function

Public Function Display() As String

End Function

Public Function MoveNext()

End Function

Public Function Update(str As String) As Boolean

End Function

Public Function FromCompact(s As String) As Long

End Function

Public Function ToCompact(n As Long) As String

End Function

Public Function FromDisplay(sFull As String) As Long

End Function

Public Function ToDisplay(dat As Date, n As Long) As String

End Function


