VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IWeldNumber"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public Function Display() As String
End Function

Public Function MoveNext()

End Function

Public Function LeaderChar() As String

End Function

Public Function Sequence() As Integer

End Function

Public Function FileName() As String

End Function

Public Function Update(strWeldNumber As String) As Boolean

End Function
